/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Test } from './ERC20Test.js';
export type { FiatTokenTest } from './FiatTokenTest.js';
export type { XERC20LockboxTest } from './XERC20LockboxTest.js';
export type { XERC20Test } from './XERC20Test.js';
export type { XERC20VSTest } from './XERC20VSTest.js';
