
[package]
name = "hyperlane-cosmos"
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bech32 = { workspace = true }
cometbft = { workspace = true, features = ["secp256k1"] }
cometbft-rpc = { workspace = true, features = ["http-client","secp256k1"] }
cosmrs = { workspace = true, features = ["tokio", "grpc", "rpc"] }
crypto = { path = "../../utils/crypto" }
derive-new = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-tls = { workspace = true }
ibc-proto = { workspace = true }
itertools = { workspace = true }
pin-project.workspace = true
prost = { version = "0.13", default-features = true }
ripemd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
sha256 = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = [
    "transport",
    "tls",
    "tls-roots",
    "tls-native-roots",
] }
tower.workspace = true
tracing = { workspace = true }
tracing-futures = { workspace = true }
url = { workspace = true }
hyperlane-cosmos-rs = { workspace = true }


hyperlane-core = { path = "../../hyperlane-core", features = ["async"] }
hyperlane-metric = { path = "../../hyperlane-metric" }
hyperlane-operation-verifier = { path = "../../applications/hyperlane-operation-verifier" }
hyperlane-warp-route = { path = "../../applications/hyperlane-warp-route" }
