arbitrum:
  submitter:
    chain: ethereum
    destinationChain: arbitrum
    internalSubmitter:
      chain: ethereum
      safeAddress: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
      type: gnosisSafeTxBuilder
      version: '1.0'
    owner: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
    type: interchainAccount
base:
  submitter:
    chain: ethereum
    destinationChain: base
    internalSubmitter:
      chain: ethereum
      safeAddress: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
      type: gnosisSafeTxBuilder
      version: '1.0'
    owner: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
    type: interchainAccount
bsc:
  submitter:
    chain: ethereum
    destinationChain: bsc
    internalSubmitter:
      chain: ethereum
      safeAddress: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
      type: gnosisSafeTxBuilder
      version: '1.0'
    owner: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
    type: interchainAccount
ethereum:
  submitter:
    chain: ethereum
    safeAddress: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
    type: gnosisSafeTxBuilder
    version: '1.0'
polygon:
  submitter:
    chain: ethereum
    destinationChain: polygon
    internalSubmitter:
      chain: ethereum
      safeAddress: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
      type: gnosisSafeTxBuilder
      version: '1.0'
    owner: '0x3965AC3D295641E452E0ea896a086A9cD7C6C5b6'
    type: interchainAccount
