deploy-mailbox-b3:
    export HYPERLANE_DOMAIN_ID=1993 && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url https://sepolia.b3.fun/http \
        --broadcast \
        -vvvv

deploy-mailbox-ape:
    export HYPERLANE_DOMAIN_ID=33111 && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url https://curtis.rpc.caldera.xyz/http \
        --broadcast \
        -vvvv

deploy-polymer-ism-b3:
    export ORIGIN_MAILBOX_ADDRESS="0xf1989fcad86f040b2bbfced6a0ce359e1247a611" && \
    export POLYMER_PROVER_ADDRESS="0xcDa03d74DEc5B24071D1799899B2e0653C24e5Fa" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url https://sepolia.b3.fun/http \
        --broadcast \
        -vvvv

deploy-polymer-ism-ape:
    export ORIGIN_MAILBOX_ADDRESS="0xf1989fcad86f040b2bbfced6a0ce359e1247a611" && \
    export POLYMER_PROVER_ADDRESS="0xcDa03d74DEc5B24071D1799899B2e0653C24e5Fa" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url https://curtis.rpc.caldera.xyz/http \
        --broadcast \
        -vvvv

deploy-simple-app-b3:
    export MAILBOX_ADDRESS="0xf1989fcad86f040b2bbfced6a0ce359e1247a611" && \
    export POLYMER_ISM_ADDRESS="0x78dd032b4f70abe632ffbd6565f0ca94091fbe6e" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url https://sepolia.b3.fun/http \
        --broadcast \
        -vvvv

deploy-simple-app-ape:
    export MAILBOX_ADDRESS="0xf1989fcad86f040b2bbfced6a0ce359e1247a611" && \
    export POLYMER_ISM_ADDRESS="0x78dd032b4f70abe632ffbd6565f0ca94091fbe6e" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url https://curtis.rpc.caldera.xyz/http \
        --broadcast \
        -vvvv

send-message-b3-to-ape:
    # Set the address of the SimpleMessageSenderReceiver deployed on B3 
    export SENDER_CONTRACT_ADDRESS="0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
    # Set the Hyperlane Domain ID of the destination (Ape Curtis = 33111)
    export DESTINATION_DOMAIN=33111
    # Set the address of the SimpleMessageSenderReceiver deployed on Ape
    export RECIPIENT_CONTRACT_ADDRESS="0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
    # Set the message content
    export MESSAGE_CONTENT="Hello from B3 to Ape!"
    forge script script/SendMessage.s.sol:SendMessage \
        --rpc-url https://sepolia.b3.fun/http \
        --broadcast \
        -vvvv

send-message-ape-to-b3:
    # Set the address of the SimpleMessageSenderReceiver deployed on Ape (curtis)
    export SENDER_CONTRACT_ADDRESS="0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
    # Set the Hyperlane Domain ID of the destination (B3 Sepolia = 1993)
    export DESTINATION_DOMAIN=1993
    # Set the address of the SimpleMessageSenderReceiver deployed on B3 (sepolia)
    export RECIPIENT_CONTRACT_ADDRESS="0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
    # Set the message content
    export MESSAGE_CONTENT="Hello from Ape Curtis to B3 Sepolia!"
    forge script script/SendMessage.s.sol:SendMessage \
        --rpc-url https://curtis.rpc.caldera.xyz/http \
        --broadcast \
        -vvvv
