rpc_endpoint_b3 := "https://sepolia.b3.fun/http"
rpc_endpoint_ape := "https://curtis.rpc.caldera.xyz/http"
rpc_endpoint_everclear_staging := "https://rpc.everclear.raas.gelato.cloud"
rpc_endpoint_base := "https://mainnet.base.org"
chain_id_b3 := "1993"
chain_id_ape := "33111"
chain_id_everclear_staging := "25327"
chain_id_base := "8453"
polymer_prover_addr := "0xcDa03d74DEc5B24071D1799899B2e0653C24e5Fa"
mailbox_contract_addr_b3 := "0x840e5aada7a7aab5f06c5d3152512a246792183f"
mailbox_contract_addr_ape := "0xd3dd44aadd6c790322c3a8da37d6b9a6d72f5c28"
mailbox_contract_addr_everclear_staging := "0xd84ab43d7f2f99339657e4bfae3c955be8d3099c"
mailbox_contract_addr_base := "0xd84ab43d7f2f99339657e4bfae3c955be8d3099c"
polymer_ism_addr_b3 := "0x5615c90c3142ebbb5bba6dde1616251581d1f16c"
polymer_ism_addr_ape := "0x5dfe4bb5aa44e459980ac1804aea4593af088cb9"
polymer_ism_addr_everclear_staging := "0x78dd032b4f70abe632ffbd6565f0ca94091fbe6e"
polymer_ism_addr_base := "0x78dd032b4f70abe632ffbd6565f0ca94091fbe6e"
default_fallback_routing_ism_addr_b3 := "0x201d9d1da9a31dd8966f54e3466f615b72e53c46"
default_fallback_routing_ism_addr_ape := "0xb9579911530c36165c9e3f09ed02af47763b4fbc"
default_fallback_routing_ism_addr_everclear_staging := "0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
default_fallback_routing_ism_addr_base := "0xd65edbd069ccc6342d0d5c23a2ee72c3237990db"
default_mailbox_contract_addr_everclear_staging := "0x7f50C5776722630a0024fAE05fDe8b47571D7B39"
default_mailbox_contract_addr_base := "0xeA87ae93Fa0019a82A727bfd3eBd1cFCa8f64f1D"
domain_routing_mailbox_addr_everclear_staging := "0x46cb3da13fd222887ef869e2db5ab73c854fcf0d"
domain_routing_mailbox_addr_base := "0x46cb3da13fd222887ef869e2db5ab73c854fcf0d"
simple_sender_receiver_addr_b3 := "0xf689811ed7fed46ae6ca9251d62d9d1cc528ba5a"
simple_sender_receiver_addr_ape := "0x840e5aada7a7aab5f06c5d3152512a246792183f"
simple_sender_receiver_addr_everclear_staging := "0x8abcae02b22a5267a94689f417824eff177da0df"
simple_sender_receiver_addr_base := "0x8abcae02b22a5267a94689f417824eff177da0df"

deploy-mailbox-b3:
    export HYPERLANE_DOMAIN_ID="{{ chain_id_b3 }}" && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url "{{ rpc_endpoint_b3 }}" \
        --broadcast \
        -vvvv

deploy-mailbox-ape:
    export HYPERLANE_DOMAIN_ID="{{ chain_id_ape }}" && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url "{{ rpc_endpoint_ape }}" \
        --broadcast \
        -vvvv

deploy-mailbox-base:
    export HYPERLANE_DOMAIN_ID="{{ chain_id_base }}" && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url "{{ rpc_endpoint_base }}" \
        --broadcast \
        -vvvv

deploy-mailbox-everclear-staging:
    export HYPERLANE_DOMAIN_ID="{{ chain_id_everclear_staging }}" && \
    forge script script/DeployMailbox.s.sol:DeployMailbox \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

deploy-polymer-ism-b3:
    export ORIGIN_MAILBOX_ADDRESS="{{ mailbox_contract_addr_ape }}" && \
    export POLYMER_PROVER_ADDRESS="{{ polymer_prover_addr }}" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url "{{ rpc_endpoint_b3 }}" \
        --broadcast \
        -vvvv

deploy-polymer-ism-ape:
    export ORIGIN_MAILBOX_ADDRESS="{{ mailbox_contract_addr_b3 }}" && \
    export POLYMER_PROVER_ADDRESS="{{ polymer_prover_addr }}" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url "{{ rpc_endpoint_ape }}" \
        --broadcast \
        -vvvv

deploy-polymer-ism-base:
    export ORIGIN_MAILBOX_ADDRESS="{{ mailbox_contract_addr_everclear_staging }}" && \
    export POLYMER_PROVER_ADDRESS="{{ polymer_prover_addr }}" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url "{{ rpc_endpoint_base }}" \
        --broadcast \
        -vvvv

deploy-polymer-ism-everclear-staging:
    export ORIGIN_MAILBOX_ADDRESS="{{ mailbox_contract_addr_base }}" && \
    export POLYMER_PROVER_ADDRESS="{{ polymer_prover_addr }}" && \
    forge script script/DeployPolymerIsm.s.sol:DeployPolymerIsm \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

deploy-default-fallback-routing-ism-b3:
    export LOCAL_MAILBOX_ADDRESS="{{ mailbox_contract_addr_b3 }}" && \
    export REMOTE_ORIGIN_DOMAIN_ID="{{ chain_id_ape }}" && \
    export POLYMER_ISM_FOR_REMOTE_ORIGIN_ADDRESS="{{ polymer_ism_addr_b3 }}" && \
    forge script script/DeployDefaultFallbackRoutingIsm.s.sol:DeployDefaultFallbackRoutingIsm \
        --rpc-url "{{ rpc_endpoint_b3 }}" \
        --broadcast \
        -vvvv

deploy-default-fallback-routing-ism-ape:
    export LOCAL_MAILBOX_ADDRESS="{{ mailbox_contract_addr_ape }}" && \
    export REMOTE_ORIGIN_DOMAIN_ID="{{ chain_id_b3 }}" && \
    export POLYMER_ISM_FOR_REMOTE_ORIGIN_ADDRESS="{{ polymer_ism_addr_ape }}" && \
    forge script script/DeployDefaultFallbackRoutingIsm.s.sol:DeployDefaultFallbackRoutingIsm \
        --rpc-url "{{ rpc_endpoint_ape }}" \
        --broadcast \
        -vvvv

deploy-default-fallback-routing-ism-everclear-staging:
    export LOCAL_MAILBOX_ADDRESS="{{ mailbox_contract_addr_everclear_staging }}" && \
    export REMOTE_ORIGIN_DOMAIN_ID="{{ chain_id_base }}" && \
    export POLYMER_ISM_FOR_REMOTE_ORIGIN_ADDRESS="{{ polymer_ism_addr_everclear_staging }}" && \
    forge script script/DeployDefaultFallbackRoutingIsm.s.sol:DeployDefaultFallbackRoutingIsm \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

deploy-default-fallback-routing-ism-base:
    export LOCAL_MAILBOX_ADDRESS="{{ mailbox_contract_addr_base }}" && \
    export REMOTE_ORIGIN_DOMAIN_ID="{{ chain_id_everclear_staging }}" && \
    export POLYMER_ISM_FOR_REMOTE_ORIGIN_ADDRESS="{{ polymer_ism_addr_base }}" && \
    forge script script/DeployDefaultFallbackRoutingIsm.s.sol:DeployDefaultFallbackRoutingIsm \
        --rpc-url "{{ rpc_endpoint_base }}" \
        --broadcast \
        -vvvv

deploy-domain-routing-mailbox-everclear-staging:
    export DEFAULT_MAILBOX_ADDRESS="{{ default_mailbox_contract_addr_everclear_staging }}" && \
    forge script script/DeployDomainRoutingMailbox.s.sol:DeployDomainRoutingMailbox \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

deploy-domain-routing-mailbox-base:
    export DEFAULT_MAILBOX_ADDRESS="{{ default_mailbox_contract_addr_base }}" && \
    forge script script/DeployDomainRoutingMailbox.s.sol:DeployDomainRoutingMailbox \
        --rpc-url "{{ rpc_endpoint_base }}" \
        --broadcast \
        -vvvv

configure-domain-routing-mailbox-everclear-staging:
    export DOMAIN_ROUTING_MAILBOX_ADDRESS="{{ domain_routing_mailbox_addr_everclear_staging }}" && \
    export DOMAIN_ID="{{ chain_id_base }}" && \
    export DOMAIN_MAILBOX_ADDRESS="{{ mailbox_contract_addr_everclear_staging }}" && \
    forge script script/ConfigureDomainRoutingMailbox.s.sol:ConfigureDomainRoutingMailbox \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

deploy-simple-app-b3:
    export MAILBOX_ADDRESS="{{ mailbox_contract_addr_b3 }}" && \
    export ISM_ADDRESS="{{ default_fallback_routing_ism_addr_b3 }}" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url "{{ rpc_endpoint_b3 }}" \
        --broadcast \
        -vvvv

deploy-simple-app-ape:
    export MAILBOX_ADDRESS="{{ mailbox_contract_addr_ape }}" && \
    export ISM_ADDRESS="{{ default_fallback_routing_ism_addr_ape }}" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url "{{ rpc_endpoint_ape }}" \
        --broadcast \
        -vvvv

deploy-simple-app-base:
    export MAILBOX_ADDRESS="{{ domain_routing_mailbox_addr_base }}" && \
    export ISM_ADDRESS="{{ polymer_ism_addr_base }}" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url "{{ rpc_endpoint_base }}" \
        --broadcast \
        -vvvv

deploy-simple-app-everclear-staging:
    export MAILBOX_ADDRESS="{{ domain_routing_mailbox_addr_everclear_staging }}" && \
    export ISM_ADDRESS="{{ polymer_ism_addr_everclear_staging }}" && \
    forge script script/DeploySimpleMessageSenderReceiver.s.sol:DeploySimpleMessageSenderReceiver \
        --rpc-url "{{ rpc_endpoint_everclear_staging }}" \
        --broadcast \
        -vvvv

send-message-b3-to-ape:
    export SENDER_CONTRACT_ADDRESS="{{ simple_sender_receiver_addr_b3 }}" && \
    export DESTINATION_DOMAIN="{{ chain_id_ape }}" && \
    export RECIPIENT_CONTRACT_ADDRESS="{{ simple_sender_receiver_addr_ape }}" && \
    export MESSAGE_CONTENT="Hello from B3 to Ape!" && \
    forge script script/SendMessage.s.sol:SendMessage \
        --rpc-url "{{ rpc_endpoint_b3 }}" \
        --broadcast \
        -vvvv

send-message-ape-to-b3:
    export SENDER_CONTRACT_ADDRESS="{{ simple_sender_receiver_addr_ape }}" && \
    export DESTINATION_DOMAIN="{{ chain_id_b3 }}" && \
    export RECIPIENT_CONTRACT_ADDRESS="{{ simple_sender_receiver_addr_b3 }}" && \
    export MESSAGE_CONTENT="Hello from Ape Curtis to B3 Sepolia!" && \
    forge script script/SendMessage.s.sol:SendMessage \
        --rpc-url "{{ rpc_endpoint_ape }}" \
        --broadcast \
        -vvvv

test-mailbox-contract-deployment-b3:
    cast call "{{ mailbox_contract_addr_b3 }}" "requiredHook()" --rpc-url "{{ rpc_endpoint_b3 }}"
    cast call "{{ mailbox_contract_addr_b3 }}" "nonce()" --rpc-url "{{ rpc_endpoint_b3 }}"

test-mailbox-contract-deployment-ape:
    cast call "{{ mailbox_contract_addr_ape }}" "requiredHook()" --rpc-url "{{ rpc_endpoint_ape }}"
    cast call "{{ mailbox_contract_addr_ape }}" "nonce()" --rpc-url "{{ rpc_endpoint_ape }}"

