strategy:
  chains:
    avalanche:
      bridge: '0x0E8Bc62865F539889fe7d8537F2ed6db5aa0F677'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 1000
      weighted:
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
        weight: 33 # should have 33% of all the collateral in this route
    base:
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 1000
      weighted:
        tolerance: 5
        weight: 33
    ethereum:
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 1000
      weighted:
        tolerance: 7
        weight: 34
  rebalanceStrategy: weighted
warpRouteId: USDC/electroneum
