strategy:
  chains:
    arbitrum:
      bridge: '0x4c19c653a8419A475d9B6735511cB81C15b8d9b2'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      weighted:
        tolerance: 5
        weight: 20
    base:
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      weighted:
        tolerance: 5
        weight: 20
    ethereum:
      bridge: '0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      weighted:
        tolerance: 5
        weight: 20
    optimism:
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      weighted:
        tolerance: 5
        weight: 20
    polygon:
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      weighted:
        tolerance: 5
        weight: 20
  rebalanceStrategy: weighted
warpRouteId: USDC/eni
