strategy:
  chains:
    arbitrum:
      bridge: '0x8a82186EA618b91D13A2041fb7aC31Bf01C02aD2'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      weighted:
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
        weight: 33
    base:
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      weighted:
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
        weight: 33
    ethereum:
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      weighted:
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
        weight: 34
  rebalanceStrategy: weighted
warpRouteId: USDC/mantra
