strategy:
  chains:
    base:
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3000
      weighted:
        tolerance: 5 # 5% deviation tolerance
        weight: 60
    ethereum:
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3000
      weighted:
        tolerance: 5 # 5% deviation tolerance
        weight: 40
  rebalanceStrategy: weighted
warpRouteId: USDC/matchain
