#!/usr/bin/env bash
# Script to generate workspace-grouped changelog for rust agents
set -euo pipefail

# Determine script directory and repo structure
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUST_MAIN_DIR="$SCRIPT_DIR/../main"

# Get the commit range
if [ $# -eq 0 ]; then
    # No arguments - use unreleased commits
    LATEST_TAG=$(git tag -l "agents-v*" --sort=-version:refname | grep -E "^agents-v[0-9]+\.[0-9]+\.[0-9]+$" | head -1 || echo "")
    if [ -z "$LATEST_TAG" ]; then
        COMMIT_RANGE="HEAD"
    else
        COMMIT_RANGE="${LATEST_TAG}..HEAD"
    fi
else
    COMMIT_RANGE="$1"
fi

# Temporary directory for categorization
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Extract workspace members from rust/main/Cargo.toml
WORKSPACE_MEMBERS=$(grep -A 100 '^\[workspace\]' "$RUST_MAIN_DIR/Cargo.toml" | sed -n '/^members = \[/,/^\]/p' | grep '"' | sed 's/[", ]//g')

# Get all commits in the range (filter to rust/main directory)
git log --no-merges --format="%H" $COMMIT_RANGE -- rust/main | while read -r commit_hash; do
    # Get commit message
    commit_msg=$(git log -1 --format="%s" "$commit_hash")
    short_hash=$(echo "$commit_hash" | cut -c1-7)

    # Get files changed in this commit (within rust/main)
    files=$(git diff-tree --no-commit-id --name-only -r "$commit_hash" -- rust/main)

    # Categorize based on workspace membership
    workspace=""
    for file in $files; do
        # Strip rust/main/ prefix if present
        file=$(echo "$file" | sed 's|^rust/main/||')

        # Check which workspace this file belongs to
        for member in $WORKSPACE_MEMBERS; do
            if [[ "$file" =~ ^"$member"(/|$) ]]; then
                workspace="$member"
                break 2  # Break both loops
            fi
        done
    done

    # Default to "Other" if no workspace found
    if [ -z "$workspace" ]; then
        workspace="Other"
    fi

    # Sanitize workspace name for file system (replace / with __)
    workspace_file=$(echo "$workspace" | tr '/' '_')

    # Store commit in workspace category file
    echo "$workspace|$commit_msg|$short_hash" >> "$TEMP_DIR/$workspace_file"
done

# Process workspace members in the order they appear in Cargo.toml, then "Other"
for workspace in $WORKSPACE_MEMBERS "Other"; do
    workspace_file=$(echo "$workspace" | tr '/' '_')

    if [ -f "$TEMP_DIR/$workspace_file" ]; then
        echo "### $workspace"
        echo ""

        # Sort and deduplicate commits (extract workspace name, msg, hash)
        sort -u "$TEMP_DIR/$workspace_file" | while IFS='|' read -r ws msg hash; do
            echo "* $msg (#$hash)"
        done
        echo ""
    fi
done

echo "<!-- generated by workspace changelog script -->"
