image:
  repository: us-east1-docker.pkg.dev/abacus-labs-dev/hyperlane/hyperlane-universal-router-engine
  tag: latest
  digest: ''
  pullPolicy: IfNotPresent

imagePullSecrets: []

hyperlane:
  runEnv: mainnet3
  registryUri: https://github.com/hyperlane-xyz/hyperlane-registry
  chains: []

replicas: 1
port: 8080
prometheus_port: 9090

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 4Gi

env:
  - name: PORT
    value: '8080'
  - name: PROMETHEUS_PORT
    value: '9090'
  - name: PUBLIC_METRICS_ENABLED
    value: 'false'
  - name: ROUTE_CACHE_PATH
    value: '/cache/route-cache.json'
  - name: CHAIN_CACHE_PATH
    value: '/cache/chain-cache.json'
