export enum MINIMUM_GAS_ACTION {
  CORE_DEPLOY_GAS = 'CORE_DEPLOY_GAS',
  WARP_DEPLOY_GAS = 'WARP_DEPLOY_GAS',
  TEST_SEND_GAS = 'TEST_SEND_GAS',
  AVS_GAS = 'AVS_GAS',
}

export type MINIMUM_GAS = {
  [MINIMUM_GAS_ACTION.CORE_DEPLOY_GAS]: string;
  [MINIMUM_GAS_ACTION.WARP_DEPLOY_GAS]: string;
  [MINIMUM_GAS_ACTION.TEST_SEND_GAS]: string;
  [MINIMUM_GAS_ACTION.AVS_GAS]: string;
};
