[workspace]
resolver = "2"
members = [
    "packages/cw-trie-verifier",
    "contracts/light-clients/cw-telepathy-light-client",
    "contracts/isms/cw-hyperlane-telepathy-ism",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Hyperlane <contact@hyperlane.xyz>"]

[workspace.dependencies]
cosmwasm-schema = "1.5.0"
cosmwasm-std = "1.5.0"
cw-storage-plus = "1.2.0"
cw2 = "1.1.2"
schemars = "0.8.16"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
sha3 = "0.10.8"
hex = "0.4.3"
rlp = "0.5.2"
primitive-types = "0.12.1"
