/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

import type {
  OnEvent,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from '../../../../common.js';

export declare namespace IStaticWeightedMultisigIsm {
  export type ValidatorInfoStruct = {
    signingAddress: string;
    weight: BigNumberish;
  };

  export type ValidatorInfoStructOutput = [string, BigNumber] & {
    signingAddress: string;
    weight: BigNumber;
  };
}

export interface IStaticWeightedMultisigIsmInterface extends utils.Interface {
  functions: {
    'moduleType()': FunctionFragment;
    'validatorsAndThresholdWeight(bytes)': FunctionFragment;
    'verify(bytes,bytes)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'moduleType'
      | 'moduleType()'
      | 'validatorsAndThresholdWeight'
      | 'validatorsAndThresholdWeight(bytes)'
      | 'verify'
      | 'verify(bytes,bytes)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'moduleType',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'moduleType()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'validatorsAndThresholdWeight',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'validatorsAndThresholdWeight(bytes)',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'verify',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'verify(bytes,bytes)',
    values: [BytesLike, BytesLike],
  ): string;

  decodeFunctionResult(functionFragment: 'moduleType', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'moduleType()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'validatorsAndThresholdWeight',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'validatorsAndThresholdWeight(bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'verify(bytes,bytes)',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface IStaticWeightedMultisigIsm extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStaticWeightedMultisigIsmInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    moduleType(overrides?: CallOverrides): Promise<[number]>;

    'moduleType()'(overrides?: CallOverrides): Promise<[number]>;

    validatorsAndThresholdWeight(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
        validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
        thresholdWeight: BigNumber;
      }
    >;

    'validatorsAndThresholdWeight(bytes)'(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
        validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
        thresholdWeight: BigNumber;
      }
    >;

    verify(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'verify(bytes,bytes)'(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;
  };

  moduleType(overrides?: CallOverrides): Promise<number>;

  'moduleType()'(overrides?: CallOverrides): Promise<number>;

  validatorsAndThresholdWeight(
    _message: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
      validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
      thresholdWeight: BigNumber;
    }
  >;

  'validatorsAndThresholdWeight(bytes)'(
    _message: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
      validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
      thresholdWeight: BigNumber;
    }
  >;

  verify(
    _metadata: BytesLike,
    _message: BytesLike,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'verify(bytes,bytes)'(
    _metadata: BytesLike,
    _message: BytesLike,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  callStatic: {
    moduleType(overrides?: CallOverrides): Promise<number>;

    'moduleType()'(overrides?: CallOverrides): Promise<number>;

    validatorsAndThresholdWeight(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
        validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
        thresholdWeight: BigNumber;
      }
    >;

    'validatorsAndThresholdWeight(bytes)'(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[], BigNumber] & {
        validators: IStaticWeightedMultisigIsm.ValidatorInfoStructOutput[];
        thresholdWeight: BigNumber;
      }
    >;

    verify(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'verify(bytes,bytes)'(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    moduleType(overrides?: CallOverrides): Promise<BigNumber>;

    'moduleType()'(overrides?: CallOverrides): Promise<BigNumber>;

    validatorsAndThresholdWeight(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'validatorsAndThresholdWeight(bytes)'(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    verify(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'verify(bytes,bytes)'(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    moduleType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'moduleType()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validatorsAndThresholdWeight(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'validatorsAndThresholdWeight(bytes)'(
      _message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    verify(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'verify(bytes,bytes)'(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;
  };
}
