//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Copy)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "checkpoint_update_type"
)]
pub enum CheckpointUpdateType {
    #[sea_orm(string_value = "fraudulent")]
    Fraudulent,
    #[sea_orm(string_value = "premature")]
    Premature,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "contract_type")]
pub enum ContractType {
    #[sea_orm(string_value = "inbox")]
    Inbox,
    #[sea_orm(string_value = "interchain_gas_paymaster")]
    InterchainGasPaymaster,
    #[sea_orm(string_value = "outbox")]
    Outbox,
    #[sea_orm(string_value = "validator_manager")]
    ValidatorManager,
}
