environment: mainnet

hyperlane:
  runEnv: mainnet3

secrets:
  prefix: 'hyperlane-mainnet3'

ingress:
  host: tollkeeper.services.hyperlane.xyz
  staticIpName: tollkeeper-mainnet

cloudArmor:
  policyName: tollkeeper-mainnet-policy

env:
  - name: SERVER_PORT
    value: '3000'
  - name: NODE_ENV
    value: 'production'
