environment: testnet

hyperlane:
  runEnv: testnet4

secrets:
  prefix: 'hyperlane-testnet4'

ingress:
  host: testnet-tollkeeper.services.hyperlane.xyz
  staticIpName: tollkeeper-testnet

cloudArmor:
  policyName: tollkeeper-testnet-policy

env:
  - name: SERVER_PORT
    value: '3000'
  - name: NODE_ENV
    value: 'production'
