/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Provider } from '@ethersproject/providers';
import { Contract, Signer, utils } from 'ethers';

import type {
  IRemoteChallenger,
  IRemoteChallengerInterface,
} from '../../../../contracts/interfaces/avs/IRemoteChallenger.js';

const _abi = [
  {
    inputs: [],
    name: 'challengeDelayBlocks',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'operator',
        type: 'address',
      },
    ],
    name: 'handleChallenge',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class IRemoteChallenger__factory {
  static readonly abi = _abi;
  static createInterface(): IRemoteChallengerInterface {
    return new utils.Interface(_abi) as IRemoteChallengerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IRemoteChallenger {
    return new Contract(address, _abi, signerOrProvider) as IRemoteChallenger;
  }
}
