[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = "preserve"
quote_style = "double"
number_underscore = "preserve"
hex_underscore = "preserve"
single_line_statement_blocks = "preserve"
multiline_func_header = "params_first_multi"
docs_style = "preserve"
single_line_imports = true
