externalBridges:
  lifi:
    integrator: 'rebalancer'
inventorySigner: '0x6056e8E8e5Db30ffa9d721e3D73b3D558011FdA9'
strategy:
  chains:
    arbitrum:
      bridgeMinAcceptedAmount: 1
      executionType: inventory
      externalBridge: lifi
      weighted:
        tolerance: 5
        weight: 25
    base:
      bridgeMinAcceptedAmount: 1
      executionType: inventory
      externalBridge: lifi
      weighted:
        tolerance: 5
        weight: 25
    ethereum:
      bridgeMinAcceptedAmount: 1
      executionType: inventory
      externalBridge: lifi
      weighted:
        tolerance: 5
        weight: 25
    optimism:
      bridgeMinAcceptedAmount: 1
      executionType: inventory
      externalBridge: lifi
      weighted:
        tolerance: 5
        weight: 25
  rebalanceStrategy: weighted
warpRouteId: ETH/viction
