{{- if .Values.hyperlane.scraperProxy.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "agent-common.fullname" . }}-external-secret
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
  annotations:
    update-on-redeploy: "{{ now }}"
spec:
  secretStoreRef:
    name: {{ include "agent-common.secret-store.name" . }}
    kind: {{ .Values.externalSecrets.storeType }}
  refreshInterval: "1h"
  target:
    name: {{ include "agent-common.fullname" . }}-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "agent-common.labels" . | nindent 10 }}
      data:
        DATABASE_URL: {{ print "'{{ .database_url | toString }}'" }}
  data:
  - secretKey: database_url
    remoteRef:
      key: {{ printf "%s-%s-scraper3-db-read-only" .Values.hyperlane.context .Values.hyperlane.runEnv }}
{{- end }}
