/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeEstimateResponse {
    #[serde(rename = "priorityBucket")]
    pub priority_bucket: Box<models::FeeEstimateBucket>,
    #[serde(rename = "normalBuckets")]
    pub normal_buckets: Vec<models::FeeEstimateBucket>,
    #[serde(rename = "lowBuckets")]
    pub low_buckets: Vec<models::FeeEstimateBucket>,
}

impl FeeEstimateResponse {
    pub fn new(
        priority_bucket: models::FeeEstimateBucket,
        normal_buckets: Vec<models::FeeEstimateBucket>,
        low_buckets: Vec<models::FeeEstimateBucket>,
    ) -> FeeEstimateResponse {
        FeeEstimateResponse {
            priority_bucket: Box::new(priority_bucket),
            normal_buckets,
            low_buckets,
        }
    }
}
