/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashrateHistoryResponse {
    #[serde(rename = "daaScore")]
    pub daa_score: i64,
    #[serde(rename = "blueScore")]
    pub blue_score: i64,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "date_time")]
    pub date_time: String,
    #[serde(rename = "bits", skip_serializing_if = "Option::is_none")]
    pub bits: Option<i64>,
    #[serde(rename = "difficulty")]
    pub difficulty: i64,
    #[serde(rename = "hashrate_kh")]
    pub hashrate_kh: i64,
}

impl HashrateHistoryResponse {
    pub fn new(daa_score: i64, blue_score: i64, timestamp: i64, date_time: String, difficulty: i64, hashrate_kh: i64) -> HashrateHistoryResponse {
        HashrateHistoryResponse {
            daa_score,
            blue_score,
            timestamp,
            date_time,
            bits: None,
            difficulty,
            hashrate_kh,
        }
    }
}

