/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    #[serde(rename = "kaspadServers")]
    pub kaspad_servers: Vec<models::KaspadResponse>,
    #[serde(rename = "database")]
    pub database: Box<models::DbCheckStatus>,
}

impl HealthResponse {
    pub fn new(
        kaspad_servers: Vec<models::KaspadResponse>,
        database: models::DbCheckStatus,
    ) -> HealthResponse {
        HealthResponse {
            kaspad_servers,
            database: Box::new(database),
        }
    }
}
