/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KaspadInfoResponse {
    #[serde(rename = "mempoolSize", skip_serializing_if = "Option::is_none")]
    pub mempool_size: Option<String>,
    #[serde(rename = "serverVersion", skip_serializing_if = "Option::is_none")]
    pub server_version: Option<String>,
    #[serde(rename = "isUtxoIndexed", skip_serializing_if = "Option::is_none")]
    pub is_utxo_indexed: Option<bool>,
    #[serde(rename = "isSynced", skip_serializing_if = "Option::is_none")]
    pub is_synced: Option<bool>,
    #[serde(rename = "p2pIdHashed", skip_serializing_if = "Option::is_none")]
    pub p2p_id_hashed: Option<String>,
}

impl KaspadInfoResponse {
    pub fn new() -> KaspadInfoResponse {
        KaspadInfoResponse {
            mempool_size: None,
            server_version: None,
            is_utxo_indexed: None,
            is_synced: None,
            p2p_id_hashed: None,
        }
    }
}
