/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionCount {
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "limit_exceeded")]
    pub limit_exceeded: bool,
}

impl TransactionCount {
    pub fn new(total: i64, limit_exceeded: bool) -> TransactionCount {
        TransactionCount {
            total,
            limit_exceeded,
        }
    }
}

