/*
 * Kaspa REST-API server
 *
 * This server is to communicate with kaspa network via REST-API
 *
 * The version of the OpenAPI document: a6a9569
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxInput {
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "index")]
    pub index: i64,
    #[serde(rename = "previous_outpoint_hash")]
    pub previous_outpoint_hash: String,
    #[serde(rename = "previous_outpoint_index")]
    pub previous_outpoint_index: String,
    #[serde(rename = "previous_outpoint_resolved", skip_serializing_if = "Option::is_none")]
    pub previous_outpoint_resolved: Option<Box<models::TxOutput>>,
    #[serde(rename = "previous_outpoint_address", skip_serializing_if = "Option::is_none")]
    pub previous_outpoint_address: Option<String>,
    #[serde(rename = "previous_outpoint_amount", skip_serializing_if = "Option::is_none")]
    pub previous_outpoint_amount: Option<i64>,
    #[serde(rename = "signature_script", skip_serializing_if = "Option::is_none")]
    pub signature_script: Option<String>,
    #[serde(rename = "sig_op_count", skip_serializing_if = "Option::is_none")]
    pub sig_op_count: Option<String>,
}

impl TxInput {
    pub fn new(transaction_id: String, index: i64, previous_outpoint_hash: String, previous_outpoint_index: String) -> TxInput {
        TxInput {
            transaction_id,
            index,
            previous_outpoint_hash,
            previous_outpoint_index,
            previous_outpoint_resolved: None,
            previous_outpoint_address: None,
            previous_outpoint_amount: None,
            signature_script: None,
            sig_op_count: None,
        }
    }
}

