image:
  repository: ghcr.io/hyperlane-xyz/hyperlane-node-services
  tag:
serviceName: warp-monitor
hyperlane:
  runEnv: mainnet3
  context: hyperlane
  chains: []
  registryUri: ''
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
