image:
  repository: ghcr.io/hyperlane-xyz/hyperlane-warp-monitor
  tag:
hyperlane:
  runEnv: mainnet3
  context: hyperlane
  chains: []
  registryUri: ''
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
