{{- if .Values.cloudArmor.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Chart.Name }}-backend-config
spec:
  securityPolicy:
    name: {{ .Values.cloudArmor.policyName }}
{{- end }}
