apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.cloudArmor.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Chart.Name }}-backend-config"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
