environment: testnet

# General deployment configuration
image:
  repository: ghcr.io/hyperlane-xyz/hyperlane-node-services
  # Modify this tag to deploy a new revision.
  # Images can be found here:
  # https://github.com/orgs/hyperlane-xyz/packages/container/package/hyperlane-node-services
  tag: 0ce6c9d-20260331-211119
serviceName: ccip-server

secrets:
  name: 'offchain-lookup-server'
  # List all secrets which are fetched from the Google Secret Store
  secret_envs:
    - DATABASE_URL

# Ingress / Loadbalancer
# Needs external coordination with Google Cloud External IP and DNS provider
# TODO move over to testnet values (and shutdown old service)
ingress:
  host: offchain-lookup.web3tools.net # Deprecated
  staticIpName: my-ingress-ip # Deprecated

port: 3000
prometheus_port: 9090
