export enum WarpRouteIds {
  Ancient8EthereumUSDC = 'USDC/ancient8-ethereum',
  ArbitrumBaseBlastBscEthereumFraxtalLineaModeOptimismSeiTaikoZircuitEZETH = 'EZETH/arbitrum-base-blast-bsc-ethereum-fraxtal-linea-mode-optimism-sei-taiko-zircuit',
  ArbitrumEthereumZircuitAMPHRETH = 'AMPHRETH/arbitrum-ethereum-zircuit',
  ArbitrumNeutronEclip = 'ECLIP/arbitrum-neutron',
  ArbitrumNeutronTIA = 'TIA/arbitrum-neutron',
  EclipseSolanaSOL = 'SOL/eclipsemainnet-solanamainnet',
  EclipseSolanaWIF = 'WIF/eclipsemainnet-solanamainnet',
  EclipseStrideSTTIA = 'stTIA/eclipse-stride',
  EclipseStrideTIA = 'TIA/eclipse-stride',
  EthereumInevmUSDC = 'USDC/ethereum-inevm',
  EthereumInevmUSDT = 'USDT/ethereum-inevm',
  EthereumEclipseTETH = 'tETH/eclipsemainnet-ethereum',
  EthereumEclipseUSDC = 'USDC/eclipsemainnet-ethereum-solanamainnet',
  EthereumSeiFastUSD = 'FASTUSD/ethereum-sei',
  EthereumVictionETH = 'ETH/ethereum-viction',
  EthereumVictionUSDC = 'USDC/ethereum-viction',
  EthereumVictionUSDT = 'USDT/ethereum-viction',
  EthereumZircuitPZETH = 'PZETH/ethereum-zircuit',
  EthereumBscLumiaLUMIA = 'LUMIA/bsc-ethereum-lumia',
  InevmInjectiveINJ = 'INJ/inevm-injective',
  MantapacificNeutronTIA = 'TIA/mantapacific-neutron',
}
