/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
} from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

import type {
  OnEvent,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from '../../../common.js';

export declare namespace DomainRoutingHook {
  export type HookConfigStruct = { destination: BigNumberish; hook: string };

  export type HookConfigStructOutput = [number, string] & {
    destination: number;
    hook: string;
  };
}

export interface DestinationRecipientRoutingHookInterface
  extends utils.Interface {
  functions: {
    'PACKAGE_VERSION()': FunctionFragment;
    'configCustomHook(uint32,bytes32,address)': FunctionFragment;
    'customHooks(uint32,bytes32)': FunctionFragment;
    'hook()': FunctionFragment;
    'hookType()': FunctionFragment;
    'hooks(uint32)': FunctionFragment;
    'interchainSecurityModule()': FunctionFragment;
    'localDomain()': FunctionFragment;
    'mailbox()': FunctionFragment;
    'owner()': FunctionFragment;
    'postDispatch(bytes,bytes)': FunctionFragment;
    'quoteDispatch(bytes,bytes)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setHook(address)': FunctionFragment;
    'setHook(uint32,address)': FunctionFragment;
    'setHooks((uint32,address)[])': FunctionFragment;
    'setInterchainSecurityModule(address)': FunctionFragment;
    'supportsMetadata(bytes)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'PACKAGE_VERSION'
      | 'PACKAGE_VERSION()'
      | 'configCustomHook'
      | 'configCustomHook(uint32,bytes32,address)'
      | 'customHooks'
      | 'customHooks(uint32,bytes32)'
      | 'hook'
      | 'hook()'
      | 'hookType'
      | 'hookType()'
      | 'hooks'
      | 'hooks(uint32)'
      | 'interchainSecurityModule'
      | 'interchainSecurityModule()'
      | 'localDomain'
      | 'localDomain()'
      | 'mailbox'
      | 'mailbox()'
      | 'owner'
      | 'owner()'
      | 'postDispatch'
      | 'postDispatch(bytes,bytes)'
      | 'quoteDispatch'
      | 'quoteDispatch(bytes,bytes)'
      | 'renounceOwnership'
      | 'renounceOwnership()'
      | 'setHook(address)'
      | 'setHook(uint32,address)'
      | 'setHooks'
      | 'setHooks((uint32,address)[])'
      | 'setInterchainSecurityModule'
      | 'setInterchainSecurityModule(address)'
      | 'supportsMetadata'
      | 'supportsMetadata(bytes)'
      | 'transferOwnership'
      | 'transferOwnership(address)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'PACKAGE_VERSION',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'PACKAGE_VERSION()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'configCustomHook',
    values: [BigNumberish, BytesLike, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'configCustomHook(uint32,bytes32,address)',
    values: [BigNumberish, BytesLike, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'customHooks',
    values: [BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'customHooks(uint32,bytes32)',
    values: [BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'hook', values?: undefined): string;
  encodeFunctionData(functionFragment: 'hook()', values?: undefined): string;
  encodeFunctionData(functionFragment: 'hookType', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'hookType()',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'hooks', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'hooks(uint32)',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'interchainSecurityModule',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'interchainSecurityModule()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'localDomain',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'localDomain()',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'mailbox', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mailbox()', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner()', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'postDispatch',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'postDispatch(bytes,bytes)',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteDispatch',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteDispatch(bytes,bytes)',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setHook(address)',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setHook(uint32,address)',
    values: [BigNumberish, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setHooks',
    values: [DomainRoutingHook.HookConfigStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'setHooks((uint32,address)[])',
    values: [DomainRoutingHook.HookConfigStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'setInterchainSecurityModule',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setInterchainSecurityModule(address)',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'supportsMetadata',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'supportsMetadata(bytes)',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership(address)',
    values: [string],
  ): string;

  decodeFunctionResult(
    functionFragment: 'PACKAGE_VERSION',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'PACKAGE_VERSION()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'configCustomHook',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'configCustomHook(uint32,bytes32,address)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'customHooks',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'customHooks(uint32,bytes32)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'hook', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hook()', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hookType', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hookType()', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hooks', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'hooks(uint32)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'interchainSecurityModule',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'interchainSecurityModule()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'localDomain',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'localDomain()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'mailbox', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mailbox()', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner()', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'postDispatch',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'postDispatch(bytes,bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'quoteDispatch',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'quoteDispatch(bytes,bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setHook(address)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setHook(uint32,address)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setHooks', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setHooks((uint32,address)[])',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setInterchainSecurityModule',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setInterchainSecurityModule(address)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'supportsMetadata',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'supportsMetadata(bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership(address)',
    data: BytesLike,
  ): Result;

  events: {
    'HookSet(address)': EventFragment;
    'Initialized(uint8)': EventFragment;
    'IsmSet(address)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'HookSet'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'HookSet(address)'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Initialized(uint8)'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'IsmSet'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'IsmSet(address)'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: 'OwnershipTransferred(address,address)',
  ): EventFragment;
}

export interface HookSetEventObject {
  _hook: string;
}
export type HookSetEvent = TypedEvent<[string], HookSetEventObject>;

export type HookSetEventFilter = TypedEventFilter<HookSetEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface IsmSetEventObject {
  _ism: string;
}
export type IsmSetEvent = TypedEvent<[string], IsmSetEventObject>;

export type IsmSetEventFilter = TypedEventFilter<IsmSetEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface DestinationRecipientRoutingHook extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DestinationRecipientRoutingHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PACKAGE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    'PACKAGE_VERSION()'(overrides?: CallOverrides): Promise<[string]>;

    configCustomHook(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'configCustomHook(uint32,bytes32,address)'(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    customHooks(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'customHooks(uint32,bytes32)'(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    hook(overrides?: CallOverrides): Promise<[string]>;

    'hook()'(overrides?: CallOverrides): Promise<[string]>;

    hookType(overrides?: CallOverrides): Promise<[number]>;

    'hookType()'(overrides?: CallOverrides): Promise<[number]>;

    hooks(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    'hooks(uint32)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<[string]>;

    'interchainSecurityModule()'(overrides?: CallOverrides): Promise<[string]>;

    localDomain(overrides?: CallOverrides): Promise<[number]>;

    'localDomain()'(overrides?: CallOverrides): Promise<[number]>;

    mailbox(overrides?: CallOverrides): Promise<[string]>;

    'mailbox()'(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    'owner()'(overrides?: CallOverrides): Promise<[string]>;

    postDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<ContractTransaction>;

    'postDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<ContractTransaction>;

    quoteDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    'quoteDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'renounceOwnership()'(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'setHook(address)'(
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'setHook(uint32,address)'(
      _destination: BigNumberish,
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setHooks(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'setHooks((uint32,address)[])'(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setInterchainSecurityModule(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'setInterchainSecurityModule(address)'(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    supportsMetadata(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    'supportsMetadata(bytes)'(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;
  };

  PACKAGE_VERSION(overrides?: CallOverrides): Promise<string>;

  'PACKAGE_VERSION()'(overrides?: CallOverrides): Promise<string>;

  configCustomHook(
    destinationDomain: BigNumberish,
    recipient: BytesLike,
    hook: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'configCustomHook(uint32,bytes32,address)'(
    destinationDomain: BigNumberish,
    recipient: BytesLike,
    hook: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  customHooks(
    arg0: BigNumberish,
    arg1: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  'customHooks(uint32,bytes32)'(
    arg0: BigNumberish,
    arg1: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  hook(overrides?: CallOverrides): Promise<string>;

  'hook()'(overrides?: CallOverrides): Promise<string>;

  hookType(overrides?: CallOverrides): Promise<number>;

  'hookType()'(overrides?: CallOverrides): Promise<number>;

  hooks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  'hooks(uint32)'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  interchainSecurityModule(overrides?: CallOverrides): Promise<string>;

  'interchainSecurityModule()'(overrides?: CallOverrides): Promise<string>;

  localDomain(overrides?: CallOverrides): Promise<number>;

  'localDomain()'(overrides?: CallOverrides): Promise<number>;

  mailbox(overrides?: CallOverrides): Promise<string>;

  'mailbox()'(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  'owner()'(overrides?: CallOverrides): Promise<string>;

  postDispatch(
    metadata: BytesLike,
    message: BytesLike,
    overrides?: PayableOverrides & { from?: string },
  ): Promise<ContractTransaction>;

  'postDispatch(bytes,bytes)'(
    metadata: BytesLike,
    message: BytesLike,
    overrides?: PayableOverrides & { from?: string },
  ): Promise<ContractTransaction>;

  quoteDispatch(
    metadata: BytesLike,
    message: BytesLike,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  'quoteDispatch(bytes,bytes)'(
    metadata: BytesLike,
    message: BytesLike,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'renounceOwnership()'(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'setHook(address)'(
    _hook: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'setHook(uint32,address)'(
    _destination: BigNumberish,
    _hook: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  setHooks(
    configs: DomainRoutingHook.HookConfigStruct[],
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'setHooks((uint32,address)[])'(
    configs: DomainRoutingHook.HookConfigStruct[],
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  setInterchainSecurityModule(
    _module: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'setInterchainSecurityModule(address)'(
    _module: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  supportsMetadata(
    arg0: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  'supportsMetadata(bytes)'(
    arg0: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  'transferOwnership(address)'(
    newOwner: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  callStatic: {
    PACKAGE_VERSION(overrides?: CallOverrides): Promise<string>;

    'PACKAGE_VERSION()'(overrides?: CallOverrides): Promise<string>;

    configCustomHook(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'configCustomHook(uint32,bytes32,address)'(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    customHooks(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    'customHooks(uint32,bytes32)'(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    hook(overrides?: CallOverrides): Promise<string>;

    'hook()'(overrides?: CallOverrides): Promise<string>;

    hookType(overrides?: CallOverrides): Promise<number>;

    'hookType()'(overrides?: CallOverrides): Promise<number>;

    hooks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    'hooks(uint32)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<string>;

    'interchainSecurityModule()'(overrides?: CallOverrides): Promise<string>;

    localDomain(overrides?: CallOverrides): Promise<number>;

    'localDomain()'(overrides?: CallOverrides): Promise<number>;

    mailbox(overrides?: CallOverrides): Promise<string>;

    'mailbox()'(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    'owner()'(overrides?: CallOverrides): Promise<string>;

    postDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    'postDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    quoteDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'quoteDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>;

    'setHook(address)'(_hook: string, overrides?: CallOverrides): Promise<void>;

    'setHook(uint32,address)'(
      _destination: BigNumberish,
      _hook: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setHooks(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    'setHooks((uint32,address)[])'(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: CallOverrides,
    ): Promise<void>;

    setInterchainSecurityModule(
      _module: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setInterchainSecurityModule(address)'(
      _module: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    supportsMetadata(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    'supportsMetadata(bytes)'(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {
    'HookSet(address)'(_hook?: null): HookSetEventFilter;
    HookSet(_hook?: null): HookSetEventFilter;

    'Initialized(uint8)'(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    'IsmSet(address)'(_ism?: null): IsmSetEventFilter;
    IsmSet(_ism?: null): IsmSetEventFilter;

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    PACKAGE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    'PACKAGE_VERSION()'(overrides?: CallOverrides): Promise<BigNumber>;

    configCustomHook(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'configCustomHook(uint32,bytes32,address)'(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    customHooks(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'customHooks(uint32,bytes32)'(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    hook(overrides?: CallOverrides): Promise<BigNumber>;

    'hook()'(overrides?: CallOverrides): Promise<BigNumber>;

    hookType(overrides?: CallOverrides): Promise<BigNumber>;

    'hookType()'(overrides?: CallOverrides): Promise<BigNumber>;

    hooks(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'hooks(uint32)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<BigNumber>;

    'interchainSecurityModule()'(overrides?: CallOverrides): Promise<BigNumber>;

    localDomain(overrides?: CallOverrides): Promise<BigNumber>;

    'localDomain()'(overrides?: CallOverrides): Promise<BigNumber>;

    mailbox(overrides?: CallOverrides): Promise<BigNumber>;

    'mailbox()'(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>;

    postDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<BigNumber>;

    'postDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<BigNumber>;

    quoteDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'quoteDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'renounceOwnership()'(
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'setHook(address)'(
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'setHook(uint32,address)'(
      _destination: BigNumberish,
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    setHooks(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'setHooks((uint32,address)[])'(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    setInterchainSecurityModule(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'setInterchainSecurityModule(address)'(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    supportsMetadata(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'supportsMetadata(bytes)'(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PACKAGE_VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'PACKAGE_VERSION()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    configCustomHook(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'configCustomHook(uint32,bytes32,address)'(
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    customHooks(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'customHooks(uint32,bytes32)'(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    hook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'hook()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hookType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'hookType()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hooks(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'hooks(uint32)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    interchainSecurityModule(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'interchainSecurityModule()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    localDomain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'localDomain()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mailbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mailbox()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    postDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'postDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    quoteDispatch(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'quoteDispatch(bytes,bytes)'(
      metadata: BytesLike,
      message: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'renounceOwnership()'(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'setHook(address)'(
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'setHook(uint32,address)'(
      _destination: BigNumberish,
      _hook: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setHooks(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'setHooks((uint32,address)[])'(
      configs: DomainRoutingHook.HookConfigStruct[],
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setInterchainSecurityModule(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'setInterchainSecurityModule(address)'(
      _module: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    supportsMetadata(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'supportsMetadata(bytes)'(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;
  };
}
