// Placing them here instead of adjacent chains file to avoid circular dep
export const testnet4SupportedChainNames = [
  'abstracttestnet',
  'alephzeroevmtestnet',
  'alfajores',
  'arbitrumsepolia',
  'arcadiatestnet2',
  'auroratestnet',
  'basesepolia',
  'bsctestnet',
  'camptestnet',
  'carrchaintestnet',
  'chronicleyellowstone',
  'citreatestnet',
  'connextsepolia',
  'cotitestnet',
  'ecotestnet',
  'eclipsetestnet',
  'flametestnet',
  'formtestnet',
  'fuji',
  'holesky',
  'hyperliquidevmtestnet',
  'infinityvmmonza',
  'inksepolia',
  'kyvetestnet',
  'milkywaytestnet',
  'modetestnet',
  'monadtestnet',
  'odysseytestnet',
  'optimismsepolia',
  'paradexsepolia',
  'plumetestnet2',
  'polygonamoy',
  'scrollsepolia',
  'sepolia',
  'solanatestnet',
  'somniatestnet',
  'soneiumtestnet',
  'sonicblaze',
  'sonicsvmtestnet',
  'starknetsepolia',
  'suavetoliman',
  'subtensortestnet',
  'superpositiontestnet',
  'treasuretopaz',
  'unichaintestnet',
  'weavevmtestnet',
] as const;

export const supportedChainNames = [...testnet4SupportedChainNames];
