// Placing them here instead of adjacent chains file to avoid circular dep
export const testnet4SupportedChainNames = [
  'arbitrumsepolia',
  'arcadiatestnet2',
  'auroratestnet',
  'basecamptestnet',
  'basesepolia',
  'bsctestnet',
  'carrchaintestnet',
  'celestiatestnet',
  'celosepolia',
  'citreatestnet',
  'cotitestnet',
  'eclipsetestnet',
  'fuji',
  'giwasepolia',
  'hyperliquidevmtestnet',
  'incentivtestnet',
  'kyvetestnet',
  'megaethtestnet',
  'milkywaytestnet',
  'modetestnet',
  'monadtestnet',
  'neuratestnet',
  'nobletestnet',
  'optimismsepolia',
  'paradexsepolia',
  'polygonamoy',
  'radixtestnet',
  'scrollsepolia',
  'sepolia',
  'solanatestnet',
  'somniatestnet',
  'sonicsvmtestnet',
  'starknetsepolia',
  'subtensortestnet',
] as const;

export const supportedChainNames = [...testnet4SupportedChainNames];
