hyperlane:
  runEnv: mainnet3

ingress:
  host: quoting.services.hyperlane.xyz
  staticIpName: quoting-mainnet

env:
  - name: PORT
    value: '8080'
  - name: QUOTE_MODE
    value: 'transient'
  - name: WARP_ROUTE_IDS
    value: 'USDC/quoted-calls-demo,USDC/ctusd,USDT/ctusd'
