image:
  repository: ghcr.io/hyperlane-xyz/hyperlane-node-services
  tag: latest
serviceName: keyfunder
hyperlane:
  runEnv: testnet4
  chains: []
  chainsToSkip: []
  registryUri: ''
  keyfunderConfig: ''
  skipIgpClaim: false
  prometheusPushGateway: ''
cronjob:
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 10
externalSecrets:
  clusterSecretStore:
