/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from './extensions/index.js';

export type { extensions };
export type { ERC721Upgradeable } from './ERC721Upgradeable.js';
export type { IERC721ReceiverUpgradeable } from './IERC721ReceiverUpgradeable.js';
export type { IERC721Upgradeable } from './IERC721Upgradeable.js';
