{
 "title": "Validator Dashboard (External Sharing Template)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Signed checkpoint diffs (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(chain) (increase (hyperlane_latest_checkpoint{agent=\"validator\", phase=\"validator_processed\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block diffs (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(hyperlane_block_height{agent=\"validator\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error log count diffs (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (pod) (increase(hyperlane_span_events_total{agent=\"validator\", event_level=\"error\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning log count diffs (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (pod) (increase(hyperlane_span_events_total{agent=\"validator\", event_level=\"warn\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}