name: 'Check Job Status'
description: 'Check the result of a job and print a message'
inputs:
  job_name:
    description: 'The name of the job'
    required: true
  result:
    description: 'The result of the job'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check job status
      shell: bash
      env:
        RESULT: ${{ inputs.result }}
        JOB_NAME: ${{ inputs.job_name }}
      run: |
        if [[ "$RESULT" == "skipped" ]]; then
          echo "$JOB_NAME was skipped!"
        elif [[ "$RESULT" != "success" ]]; then
          echo "$JOB_NAME failed"
          exit 1
        fi
