warpRouteId: USDTSTAGE/mode

inventorySigners:
    ethereum:
        address: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"

externalBridges:
    lifi:
        integrator: "rebalancer"
    layerzero: {}

strategy:
    rebalanceStrategy: weighted
    chains:
        ethereum:
            weighted:
                weight: 10
                tolerance: 5
            executionType: inventory
            externalBridge: layerzero

        arbitrum:
            weighted:
                weight: 10
                tolerance: 5
            executionType: inventory
            externalBridge: layerzero

        plasma:
            weighted:
                weight: 80
                tolerance: 5
            executionType: inventory
            externalBridge: layerzero
