/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  owner: string;
  paused: boolean;
}
export type ExecuteMsg =
  | {
      ownable: OwnableMsg;
    }
  | {
      pausable: PausableMsg;
    }
  | {
      post_dispatch: PostDispatchMsg;
    };
export type OwnableMsg =
  | {
      init_ownership_transfer: {
        next_owner: string;
      };
    }
  | {
      revoke_ownership_transfer: {};
    }
  | {
      claim_ownership: {};
    };
export type PausableMsg =
  | {
      pause: {};
    }
  | {
      release: {};
    };
export type HexBinary = string;
export interface PostDispatchMsg {
  message: HexBinary;
  metadata: HexBinary;
}
export type QueryMsg =
  | {
      pausable: PausableQueryMsg;
    }
  | {
      ownable: OwnableQueryMsg;
    }
  | {
      hook: HookQueryMsg;
    };
export type PausableQueryMsg = {
  pause_info: {};
};
export type OwnableQueryMsg =
  | {
      get_owner: {};
    }
  | {
      get_pending_owner: {};
    };
export type HookQueryMsg =
  | {
      quote_dispatch: QuoteDispatchMsg;
    }
  | {
      mailbox: {};
    };
export interface QuoteDispatchMsg {
  message: HexBinary;
  metadata: HexBinary;
}
export type Addr = string;
export interface OwnerResponse {
  owner: Addr;
}
export interface PendingOwnerResponse {
  pending_owner?: Addr | null;
}
export interface MailboxResponse {
  mailbox: string;
}
export interface PauseInfoResponse {
  paused: boolean;
}
export type Uint128 = string;
export interface QuoteDispatchResponse {
  gas_amount?: Coin | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
