#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged

# if any *.rs files have changed
if git diff --staged --exit-code --name-only | grep -q -E ".*\.rs$"; then
    echo "Running cargo fmt pre-commit hook"
    cargo fmt --all --check --manifest-path rust/Cargo.toml
fi
