[package]
name = "abigen"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true


[dependencies]
Inflector.workspace = true
ethers = { workspace = true, optional = true }
cainome = { workspace = true, optional = true }

[features]
default = []
ethers = ["dep:ethers"]
starknet = ["dep:cainome"]
