apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-secrets
spec:
  secretStoreRef:
    name: external-secrets-gcp-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: {{ .Chart.Name }}-secrets
  data:
    - secretKey: SIGNER_PRIVATE_KEY
      remoteRef:
        key: hyperlane-{{ .Values.hyperlane.runEnv }}-key-quotesigner
        property: privateKey
    - secretKey: API_KEYS
      remoteRef:
        key: {{ .Values.hyperlane.runEnv }}-fee-quoting-api-keys
