name: Migrate aleo-tools image from GCR to GHCR
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from GCR, push to GHCR
        run: |
          docker pull gcr.io/abacus-labs-dev/hyperlane-aleo-tools:v1.0.1
          docker tag gcr.io/abacus-labs-dev/hyperlane-aleo-tools:v1.0.1 ghcr.io/hyperlane-xyz/hyperlane-aleo-tools:v1.0.1
          docker push ghcr.io/hyperlane-xyz/hyperlane-aleo-tools:v1.0.1
